# Generated by Django 5.0.2 on 2024-05-24 23:06

import django.core.validators
import django.db.models.deletion
import medicos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialidades',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='especialidades',
            new_name='especialidade',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='dia',
            field=models.DateField(help_text='Introduzca una fecha para el calendario', validators=[medicos.models.validar_dia]),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='telefono',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="El número debe tener este formato:                     '+99 99 9999-0000'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefono'),
        ),
    ]
