# Generated by Django 5.0.2 on 2024-05-24 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_rename_nombre_especialidades_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='especialidade',
            new_name='especialidades',
        ),
    ]
