# Generated by Django 5.0.2 on 2024-05-24 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='telefone',
            new_name='telefono',
        ),
    ]
